baseURL: "https://yanniscabossioras.github.io/"
title: Yannis Cabossioras
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv/
          weight: 1
        - name: Research
          url: papers/
          weight: 2
        - name: Contact
          url: contact
          weight: 3

params:
    description: "Yannis Cabossioras homepage. I am a Ph.D. candidate in Finance at NYU Stern, on the job market in 2024-2025. My topics are banking and industrial organization."
    author: Yannis Cabossioras
    googleAnalyticsID: "G-EHF6G800W0"
    
    profileMode:
          enabled: true
          title: Yannis Cabossioras
          subtitle: >
            
            Welcome! I am a Ph.D. candidate in Finance at NYU Stern, on the job market in 2024-2025.


            I am specialized in banking and industrial organization.


            <br/>


            [yannis.cabossioras@stern.nyu.edu](mailto:yannis.cabossioras@stern.nyu.edu)

          imageUrl: "Professional_square.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Yannis Cabossioras

          buttons:
            - name: CV
              url: cv/
            - name: Research
              url: papers/
            - name: Contact
              url: contact
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
    
    mainSections:
        - papers/

    socialIcons:
        - name: Linkedin
          url: https://www.linkedin.com/in/ycabossioras/
        - name: GitHub
          url: https://github.com/ycabossioras
        - name: Twitter
          url: https://twitter.com/YCabossioras
        - name: Zoom
          url: https://nyu.zoom.us/my/ycabossioras
        # - name: Location
        #   url: location/
        # - name: Contact
        #   url: officehours/
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        
    label:
      text: "Yannis Cabossioras"
      icon: favicon.ico
      iconHeight: 28

    DateFormat: "January 2006"
    defaultTheme: auto  # dark light auto
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

module:
  imports:
  - path: github.com/hugomods/google-analytics
  - path: github.com/hugomods/icons/vendors/font-awesome
  - path: github.com/hugomods/katex